<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskManagement.Domain\TaskManagement.Domain.csproj" />
    <ProjectReference Include="..\TaskManagement.Domain.Repository\TaskManagement.Domain.Repository.csproj" />
    <ProjectReference Include="..\TaskManagement.Domain.ApplicationServices\TaskManagement.Domain.ApplicationServices.csproj" />
    <ProjectReference Include="..\TaskManagement.Repository.ImplSql\TaskManagement.Repository.ImplSql.csproj" />
  </ItemGroup>

</Project>
